### ISSUE TITLE
Fix broken LinkedIn link

### ISSUE THREAD

**Issue by alishasonawalla** [nyu-ossd-s19/css459-weekly#1]
The LinkedIn link on the blog site gives a '404 Page not found' error. I believe replacing [this](https://github.com/nyu-ossd-s19/css459-weekly/blob/gh-pages/_config.yml#L34) line with 'cole-s-smith' i.e. just your username should do the trick.

**Comment by css459** [comment]
Thanks for your help!! Fixed in b592718994657b87e01765f0057b3ef3b95ac592 :)
